package components;

import dataBase.AddressListData;
import java.awt.BorderLayout;
import java.awt.Container;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import ui.AButton;
import ui.ADialog;
import ui.ATextArea;
import ui.ATextField;
import ui.ImagePanel;

import util.AResource;

public class ADLIconDetailDialog extends ADialog {

	private static final long serialVersionUID = 1L;
	private String id = "-1";
	private String name = "name";
	private String sex = "";
	private String xclass = "";
	private String NO1 = "";
	private String NO1Class = "";
	private String NO2 = "";
	private String NO2Class = "";
	private String NO3 = "";
	private String NO3Class = "";
	private String address = "";
	private String hometown = "";
	private String qq = "";
	private String email = "";
	private String remarks = "";
	private AButton pageupButton;
	private AButton pagedownButton;
	private AButton modifyButton;
	private AButton deleteButton;
	private AButton exitButton;
	private Container contenePane;
	private ATextField nameTextField;
	private ATextField classTextField;
	private ATextField sexTextField;
	private ATextField no1TextField;
	private ATextField no1ClassTextField;
	private ATextField no2TextField;
	private ATextField no2ClassTextField;
	private ATextField no3TextField;
	private ATextField no3ClassTextField;
	private ATextField addressTextField;
	private ATextField hometownTextField;
	private ATextField qqTextField;
	private ATextField emailTextField;
	private ATextArea remrksTextArea;
	private MainFrame mainFrame = null;

	public ADLIconDetailDialog(MainFrame mainFrame) {
		this.mainFrame = mainFrame;
		initCompent();
		addAction();
		setLocationRelativeTo(this.mainFrame);
	}

	private void initCompent() {
		pagedownButton = new AButton();
		pagedownButton.setIcon(AResource.getImageIcon("pagedown"));
		pageupButton = new AButton();
		pageupButton.setIcon(AResource.getImageIcon("pageup"));
		modifyButton = new AButton();
		modifyButton.setIcon(AResource.getImageIcon("modify"));
		deleteButton = new AButton();
		deleteButton.setIcon(AResource.getImageIcon("delete"));
		exitButton = new AButton();
		exitButton.setIcon(AResource.getImageIcon("exit"));
		setUndecorated(true);
		setTitle("Detail");
		contenePane = getContentPane();
		JPanel mainPanel = new ImagePanel(AResource.getWallpaper());
		mainPanel.setLayout(new BorderLayout());
		mainPanel.setBorder(BorderFactory.createEtchedBorder());
		JPanel uPanel = new JPanel();
		uPanel.setOpaque(false);
		uPanel.setLayout(new BorderLayout());
		JPanel u1Panel = new JPanel();
		u1Panel.setOpaque(false);
		u1Panel.setLayout(new BorderLayout());
		JPanel photoPanel = new JPanel();
		photoPanel.setOpaque(false);
		photoPanel.setBorder(BorderFactory.createEtchedBorder());
		JLabel photoLabel = new JLabel();
		photoLabel.setIcon(new ImageManager().getImage(id));
		photoPanel.add(photoLabel);
		u1Panel.add(photoPanel, BorderLayout.WEST);
		JPanel u12Panel = new JPanel();
		u12Panel.setOpaque(false);
		BoxLayout boxLayout = new BoxLayout(u12Panel, BoxLayout.Y_AXIS);
		u12Panel.setLayout(boxLayout);
		JPanel namePanel = new JPanel();
		namePanel.setOpaque(false);
		JLabel nameLabel = new JLabel(AResource.getLabel("name"));
		namePanel.add(nameLabel);
		nameTextField = new ATextField();
		nameTextField.setText(name);
		nameTextField.setEditable(false);
		nameTextField.setColumns(23);
		namePanel.add(nameTextField);
		u12Panel.add(namePanel);
		JPanel sexPanel = new JPanel();
		sexPanel.setOpaque(false);
		JLabel classLabel = new JLabel(AResource.getLabel("class"));
		classTextField = new ATextField();
		classTextField.setText(xclass);
		classTextField.setEditable(false);
		classTextField.setColumns(8);
		sexPanel.add(classLabel);
		sexPanel.add(classTextField);
		JLabel sexLabel = new JLabel(AResource.getLabel("sex"));
		sexTextField = new ATextField();
		sexTextField.setText(sex);
		sexTextField.setEditable(false);
		sexTextField.setColumns(8);
		sexPanel.add(sexLabel);
		sexPanel.add(sexTextField);
		u12Panel.add(sexPanel);
		JPanel no1Panel = new JPanel();
		no1Panel.setOpaque(false);
		no1TextField = new ATextField();
		no1TextField.setText(NO1);
		no1TextField.setEditable(false);
		no1TextField.setColumns(18);
		no1ClassTextField = new ATextField();
		no1ClassTextField.setText(NO1Class);
		no1ClassTextField.setEditable(false);
		no1ClassTextField.setColumns(8);
		no1Panel.add(no1TextField);
		no1Panel.add(no1ClassTextField);
		u12Panel.add(no1Panel);
		JPanel no2Panel = new JPanel();
		no2Panel.setOpaque(false);
		no2TextField = new ATextField();
		no2TextField.setText(NO2);
		no2TextField.setEditable(false);
		no2TextField.setColumns(18);
		no2ClassTextField = new ATextField();
		no2ClassTextField.setText(NO2Class);
		no2ClassTextField.setEditable(false);
		no2ClassTextField.setColumns(8);
		no2Panel.add(no2TextField);
		no2Panel.add(no2ClassTextField);
		u12Panel.add(no2Panel);
		JPanel no3Panel = new JPanel();
		no3Panel.setOpaque(false);
		no3TextField = new ATextField();
		no3TextField.setText(NO3);
		no3TextField.setEditable(false);
		no3TextField.setColumns(18);
		no3ClassTextField = new ATextField();
		no3ClassTextField.setText(NO3Class);
		no3ClassTextField.setEditable(false);
		no3ClassTextField.setColumns(8);
		no3Panel.add(no3TextField);
		no3Panel.add(no3ClassTextField);
		u12Panel.add(no3Panel);
		u1Panel.add(u12Panel, BorderLayout.CENTER);
		JPanel u2Panel = new JPanel();
		u2Panel.setOpaque(false);
		BoxLayout boxLayout2 = new BoxLayout(u2Panel, BoxLayout.Y_AXIS);
		u2Panel.setLayout(boxLayout2);
		JPanel addressPanel = new JPanel();
		addressPanel.setOpaque(false);
		JLabel addressLabel = new JLabel(AResource.getLabel("address"));
		addressTextField = new ATextField();
		addressTextField.setText(address);
		addressTextField.setEditable(false);
		addressTextField.setColumns(40);
		addressPanel.add(addressLabel);
		addressPanel.add(addressTextField);
		u2Panel.add(addressPanel);
		JPanel hometownPanel = new JPanel();
		hometownPanel.setOpaque(false);
		JLabel hometownLabel = new JLabel(AResource.getLabel("hometown"));
		hometownTextField = new ATextField();
		hometownTextField.setEditable(false);
		hometownTextField.setText(hometown);
		hometownTextField.setColumns(40);
		hometownPanel.add(hometownLabel);
		hometownPanel.add(hometownTextField);
		u2Panel.add(hometownPanel);
		JPanel qqPanel = new JPanel();
		qqPanel.setOpaque(false);
		JLabel qQLabel = new JLabel();
		qQLabel.setIcon(AResource.getImageIcon("QQ"));
		qqTextField = new ATextField();
		qqTextField.setText(qq);
		qqTextField.setEditable(false);
		qqTextField.setColumns(17);
		JLabel emailLabel = new JLabel();
		emailLabel.setIcon(AResource.getImageIcon("email"));
		emailTextField = new ATextField();
		emailTextField.setText(email);
		emailTextField.setEditable(false);
		emailTextField.setColumns(17);
		qqPanel.add(qQLabel);
		qqPanel.add(qqTextField);
		qqPanel.add(emailLabel);
		qqPanel.add(emailTextField);
		u2Panel.add(qqPanel);
		JPanel remarksPanel = new JPanel();
		JLabel remarksLabel = new JLabel();
		remarksLabel.setText(AResource.getLabel("remarks"));
		remrksTextArea = new ATextArea();
		remrksTextArea.setText(remarks);
		remrksTextArea.setEditable(false);
		remrksTextArea.setColumns(40);
		remrksTextArea.setRows(4);
		remrksTextArea.setOpaque(false);
		remarksPanel.add(remarksLabel);
		remarksPanel.add(remrksTextArea);
		remarksPanel.setOpaque(false);
		u2Panel.add(remarksPanel);
		u12Panel.setOpaque(false);
		u2Panel.setOpaque(false);
		uPanel.add(u1Panel, BorderLayout.NORTH);
		uPanel.add(u2Panel, BorderLayout.SOUTH);
		JPanel buttonPanel = new JPanel();
		buttonPanel.add(pagedownButton);
		buttonPanel.add(pageupButton);
		buttonPanel.add(modifyButton);
		buttonPanel.add(deleteButton);
		buttonPanel.add(exitButton);
		uPanel.setOpaque(false);
		buttonPanel.setOpaque(false);
		mainPanel.add(uPanel, BorderLayout.CENTER);
		mainPanel.add(buttonPanel, BorderLayout.SOUTH);
		contenePane.add(mainPanel);
		pack();
	}

	public void setData(AddressListData mainVector) {
		id = mainVector.getID();
		name = mainVector.getName();
		sex = mainVector.getSex();
		xclass = mainVector.getXClass();
		NO1 = mainVector.getNo1();
		NO1Class = mainVector.getNo1Class();
		NO2 = mainVector.getNo2();
		NO2Class = mainVector.getNo2Class();
		NO3 = mainVector.getNo3();
		NO3Class = mainVector.getNo3Class();
		address = mainVector.getAddress();
		hometown = mainVector.getHometown();
		qq = mainVector.getQQ();
		email = mainVector.getEmail();
		remarks = mainVector.getRemarks();
		loadData();
	}

	private void addAction() {
		exitButton.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				dispose();
			}
		});
	}

	private void loadData() {
		nameTextField.setText(name);
		sexTextField.setText(sex);
		no1ClassTextField.setText(NO1Class);
		no1TextField.setText(NO1);
		no2ClassTextField.setText(NO2Class);
		no2TextField.setText(NO2);
		no3ClassTextField.setText(NO3Class);
		no3TextField.setText(NO3);
		qqTextField.setText(qq);
		emailTextField.setText(email);
		remrksTextArea.setText(remarks);
		classTextField.setText(xclass);
	}
}
